# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              "https://oiy.github.io"
baseurl:          ""

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Permalinks
permalink:        pretty

# Pagination
paginate:         5

# Theme
remote_theme: poole/hyde

# Plugins (seulement ceux supportés par GitHub Pages)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
